service: myfirstserverless
app: learn-dal-project
org: vinhlam

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  region: ap-southeast-1
  timeout: 3
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
      Resource: "*"

functions:
  get-list-message:
    handler: src/BLL/notificationMessage.getMessages
    events:
      - http:
          method: get
          path: messages
          cors: true
  get-message:
    handler: src/BLL/notificationMessage.getMessage
    events:
      - http:
          method: get
          path: message
          cors: true
  create-message:
    handler: src/BLL/notificationMessage.createMessage
    events:
      - http:
          method: post
          path: message
          cors: true
  update-message:
    handler: src/BLL/notificationMessage.updateMessage
    events:
      - http:
          method: put
          path: message
          cors: true
  delete-message:
    handler: src/BLL/notificationMessage.deleteMessage
    events:
      - http:
          method: delete
          path: message
          cors: true
# resources:
#  Resources:
#   TodosDynamoDbTable:
#     Type: AWS::DynamoDB::Table
#     Properties:
#       TableName: ${self:provider.environment.DYNAMODB_TABLE}
#       AttributeDefinitions:
#         - AttributeName: messageId
#           AttributeType: S
#         - AttributeName: language
#           AttributeType: S
#       KeySchema:
#         - AttributeName: messageId
#           KeyType: HASH
#         - AttributeName: language
#           KeyType: RANGE
#       ProvisionedThroughput:
#         ReadCapacityUnits: 5
#         WriteCapacityUnits: 5
resources:
 Resources:
  iotWeatherApp:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: iotWeatherApp
      AttributeDefinitions:
        - AttributeName: thingId
          AttributeType: S
      KeySchema:
        - AttributeName: thingId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
plugins:
  - serverless-offline