import React from 'react';

const Info = () => (
  <section>
    <h1 className="title">Terms and Conditions</h1>
    <br />
    <p className="default-text">Updated July, 2020</p>
    <br />
    <p className="lower-text">
      BRAVOSUITE IS WILLING TO GRANT ACCESS TO THE SAAS PRODUCTS TO YOU AS THE COMPANY OR THE
      LEGAL ENTITY THAT WILL BE UTILIZING THE SAAS PRODUCTS (REFERENCED BELOW AS “CUSTOMER”)
      ON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS OF THIS AGREEMENT (AS DEFINED BELOW).
      BY ENTERING INTO THIS AGREEMENT ON BEHALF OF AN ENTITY OR ORGANIZATION, YOU REPRESENT THAT
      YOU HAVE THE LEGAL AUTHORITY TO BIND THAT ENTITY OR ORGANIZATION TO THIS AGREEMENT.
      CUSTOMER AND BRAVOSUITE MAY EACH ALSO BE REFERRED TO AS A “PARTY” AND TOGETHER,
      THE “PARTIES”.
    </p>
    <br />
    <p className="lower-text">
      PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THE SAAS PRODUCTS.
      THIS SAAS TERMS OF SERVICE
      {' '}
      <span className="bold">(“AGREEMENT”)</span>
      {' '}
      CONSTITUTES A LEGAL AND ENFORCEABLE
      CONTRACT BETWEEN CUSTOMER AND BRAVOSUITE. BY INDICATING CONSENT ELECTRONICALLY,
      OR ACCESSING OR OTHERWISE USING THE SAAS PRODUCTS, CUSTOMER AGREES TO THE TERMS
      AND CONDITIONS OF THIS AGREEMENT. IF CUSTOMER DOES NOT AGREE TO THIS AGREEMENT,
      DO NOT INDICATE CONSENT ELECTRONICALLY AND MAKE NO FURTHER USE OF THE SAAS PRODUCTS.
    </p>
  </section>
);

export default Info;